version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing Docker and Docker Compose"
      - apt-get update
      - apt-get install -y docker.io
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo "Building Docker image"
      - docker-compose build

  build:
    commands:
      - echo "Starting Docker containers"
      - docker-compose up -d
      - echo "Waiting for database to be ready"
      - until docker-compose exec db pg_isready -U user; do echo "Waiting for db..."; sleep 1; done
      - echo "Creating the database"
      - docker-compose exec app python create_db.py

  post_build:
    commands:
      - echo "Tagging and pushing Docker image to Amazon ECR"
      - docker tag app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest

artifacts:
  files:
    - app.py
    - create_db.py
    - docker-compose.yml
    - Dockerfile
    - drop_db.py
    - requirements.txt
