name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Docker
        run: |
          sudo apt-get install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          docker --version

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Build Docker images
        run: docker-compose build
      
      - name: Start containers
        run: docker-compose up -d
      
      - name: Run database initialization script
        run: docker-compose run app python create_db.py
